name: Render video
on:
  workflow_dispatch:
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: sudo npm run build --
      - uses: actions/upload-artifact@v2
        with:
          name: out.mp4
          path: out/video.mp4
